// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// jmspline_main
Rcpp::List jmspline_main(SEXP n, SEXP n_total, SEXP tL, SEXP tU, SEXP p01, SEXP p02, SEXP q_b, SEXP q_eta, SEXP j_max, SEXP t_max, SEXP nbreak, SEXP k_max, SEXP quadpoint, SEXP maxiter, SEXP trace, SEXP ydatanew, SEXP mdatanew, SEXP cdatanew, SEXP sigmau_invnew, SEXP tbthetanew, SEXP xs, SEXP ws);
RcppExport SEXP _JMM_jmspline_main(SEXP nSEXP, SEXP n_totalSEXP, SEXP tLSEXP, SEXP tUSEXP, SEXP p01SEXP, SEXP p02SEXP, SEXP q_bSEXP, SEXP q_etaSEXP, SEXP j_maxSEXP, SEXP t_maxSEXP, SEXP nbreakSEXP, SEXP k_maxSEXP, SEXP quadpointSEXP, SEXP maxiterSEXP, SEXP traceSEXP, SEXP ydatanewSEXP, SEXP mdatanewSEXP, SEXP cdatanewSEXP, SEXP sigmau_invnewSEXP, SEXP tbthetanewSEXP, SEXP xsSEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_total(n_totalSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tL(tLSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tU(tUSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p01(p01SEXP);
    Rcpp::traits::input_parameter< SEXP >::type p02(p02SEXP);
    Rcpp::traits::input_parameter< SEXP >::type q_b(q_bSEXP);
    Rcpp::traits::input_parameter< SEXP >::type q_eta(q_etaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type j_max(j_maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nbreak(nbreakSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k_max(k_maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type quadpoint(quadpointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ydatanew(ydatanewSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mdatanew(mdatanewSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cdatanew(cdatanewSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmau_invnew(sigmau_invnewSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tbthetanew(tbthetanewSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(jmspline_main(n, n_total, tL, tU, p01, p02, q_b, q_eta, j_max, t_max, nbreak, k_max, quadpoint, maxiter, trace, ydatanew, mdatanew, cdatanew, sigmau_invnew, tbthetanew, xs, ws));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JMM_jmspline_main", (DL_FUNC) &_JMM_jmspline_main, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_JMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
