# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jmspline_main <- function(n, n_total, tL, tU, p01, p02, q_b, q_eta, j_max, t_max, nbreak, k_max, quadpoint, maxiter, trace, ydatanew, mdatanew, cdatanew, sigmau_invnew, tbthetanew, xs, ws, beta0initnew, beta1initnew, sigmainitnew, thetainitnew, sigmadinitnew, gammainit, survvar, conversigmad) {
    .Call(`_JMM_jmspline_main`, n, n_total, tL, tU, p01, p02, q_b, q_eta, j_max, t_max, nbreak, k_max, quadpoint, maxiter, trace, ydatanew, mdatanew, cdatanew, sigmau_invnew, tbthetanew, xs, ws, beta0initnew, beta1initnew, sigmainitnew, thetainitnew, sigmadinitnew, gammainit, survvar, conversigmad)
}

bootsdata_main <- function(n, n1, tL, tU, q_eta, j_max, p01, p02, t_max, ydatanew, cdatanew, mdatanew, nboots) {
    .Call(`_JMM_bootsdata_main`, n, n1, tL, tU, q_eta, j_max, p01, p02, t_max, ydatanew, cdatanew, mdatanew, nboots)
}

Simdata_main <- function(n, sim, nbreak, tL, tU, q_eta, j_max, p01, p02, t_max, distr, m_age, std_age, k_max, tbthetanew, sigmau_invnew, tbeta0new, tbeta1new, tsigmanew, tthetanew, tsigmadnew, tetanew, tgamma, lambda0) {
    .Call(`_JMM_Simdata_main`, n, sim, nbreak, tL, tU, q_eta, j_max, p01, p02, t_max, distr, m_age, std_age, k_max, tbthetanew, sigmau_invnew, tbeta0new, tbeta1new, tsigmanew, tthetanew, tsigmadnew, tetanew, tgamma, lambda0)
}

