# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jmspline_main <- function(n, n_total, tL, tU, p01, p02, q_b, q_eta, j_max, t_max, nbreak, k_max, quadpoint, maxiter, trace, ydatanew, mdatanew, cdatanew, sigmau_invnew, tbthetanew, xs, ws) {
    .Call(`_JMM_jmspline_main`, n, n_total, tL, tU, p01, p02, q_b, q_eta, j_max, t_max, nbreak, k_max, quadpoint, maxiter, trace, ydatanew, mdatanew, cdatanew, sigmau_invnew, tbthetanew, xs, ws)
}

